In [2]:
import warnings
warnings.filterwarnings('ignore',category=FutureWarning)

import numpy as np
import tensorflow as tf

In [5]:
tensor0 = tf.placeholder(tf.bool, name='t0')
tensor1 = tf.placeholder(tf.string)
tensor2 = tf.placeholder(tf.int32)
tensor3 = tf.placeholder(tf.float64)
tensor4 = tf.placeholder(tf.complex128)

In [10]:
# create a session to run the tensors
with tf.Session() as sess:
    print(sess.run(tensor0, feed_dict={tensor0:[True, False, True]}), end='\n\n')
    print(sess.run(tensor1, feed_dict={tensor1:['AR', 'CL', 'CO']}), end='\n\n')
    print(sess.run(tensor2, feed_dict={tensor2:[1, 2, 3, 4, 5, 6]}), end='\n\n')
    print(sess.run(tensor3, feed_dict={tensor3:[1.5, 2.3, 3.6, 4.7]}), end='\n\n')
    print(sess.run(tensor4, feed_dict={tensor4:[5+3j, 4+2j, 9+3j]}), end='\n\n')

[ True False  True]

['AR' 'CL' 'CO']

[1 2 3 4 5 6]

[1.5 2.3 3.6 4.7]

[5.+3.j 4.+2.j 9.+3.j]



In [14]:
# create a session to run the tensors
with tf.Session() as sess:
    print(sess.run(tensor0, {tensor0:[False, False, True]}), end='\n\n')
    print(sess.run(tensor1, {tensor1:['AU', 'UK', 'US']}), end='\n\n')
    print(sess.run(tensor2, {tensor2:[1, 3, 5, 7, 9, 11]}), end='\n\n')
    print(sess.run(tensor3, {tensor3:[1, 3, 5, 7, 9, 11]}), end='\n\n')
    print(sess.run(tensor4, {tensor4:[1, 3, 5, 7, 9, 11]}), end='\n\n')

[False False  True]

['AU' 'UK' 'US']

[ 1  3  5  7  9 11]

[ 1.  3.  5.  7.  9. 11.]

[ 1.+0.j  3.+0.j  5.+0.j  7.+0.j  9.+0.j 11.+0.j]

