In [1]:
import warnings
warnings.filterwarnings('ignore',category=FutureWarning)

import numpy as np
import tensorflow as tf

In [2]:
# Scalar Tensor (Rank #0)
tensor0 = tf.Variable(5)
tensor1 = tf.Variable(True, tf.bool)
tensor2 = tf.Variable('Hello', tf.string)

# Vector Tensor (Rank #1)
tensor3 = tf.Variable([1, 2, 3, 4], tf.int32)

# Matrix Tensor (Rank #2)
tensor4 = tf.Variable([[1.1, 2.1], [3.1, 4.4]], tf.float64)

# Higher Dimessional Tensor
tensor5 = tf.Variable([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], tf.complex128)

In [3]:
print('Rank #0 : ', tensor0.shape, tensor0.dtype)
print('Rank #0 : ', tensor1.shape, tensor1.dtype)
print('Rank #0 : ', tensor2.shape, tensor2.dtype)
print('Rank #1 : ', tensor3.shape, tensor3.dtype)
print('Rank #2 : ', tensor4.shape, tensor4.dtype)
print('Rank #3 : ', tensor5.shape, tensor5.dtype)

Rank #0 :  () <dtype: 'int32_ref'>
Rank #0 :  () <dtype: 'bool_ref'>
Rank #0 :  () <dtype: 'string_ref'>
Rank #1 :  (4,) <dtype: 'int32_ref'>
Rank #2 :  (2, 2) <dtype: 'float32_ref'>
Rank #3 :  (2, 2, 2) <dtype: 'int32_ref'>


In [4]:
# initialize the variables
init_op = tf.global_variables_initializer()

# crate a session to run the tensors
with tf.Session() as sess:
    sess.run(init_op) #execute init_op
    
    print(sess.run(tensor0), end='\n\n')
    print(sess.run(tensor1), end='\n\n')
    print(sess.run(tensor2), end='\n\n')
    print(sess.run(tensor3), end='\n\n')
    print(sess.run(tensor4), end='\n\n')
    print(sess.run(tensor5), end='\n\n')

5

True

b'Hello'

[1 2 3 4]

[[1.1 2.1]
 [3.1 4.4]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

