In [1]:
import warnings
warnings.filterwarnings('ignore',category=FutureWarning)

import numpy as np
import tensorflow as tf

In [2]:
# Defining Constant Tensors
tensorA = tf.constant([[i+3*j for i in range(1, 4)] for j in range(3)])
tensorB = tf.constant([[i+3*j for i in range(3, 0, -1)] for j in range(3)])

In [4]:
# create a session to run the tensors
with tf.Session() as sess:
    print(sess.run(tensorA), end='\n\n')
    print(sess.run(tensorB), end='\n\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[3 2 1]
 [6 5 4]
 [9 8 7]]



In [5]:
tensor_add = tensorA + tensorB
tensor_sub = tensorA - tensorB
tensor_mul = tensorA * tensorB
tensor_div = tensorA / tensorB
tensor_mod = tensorA % tensorB

In [6]:
# create a session to run the tensors
with tf.Session() as sess:
    print(sess.run(tensor_add), end='\n\n')
    print(sess.run(tensor_sub), end='\n\n')
    print(sess.run(tensor_mul), end='\n\n')
    print(sess.run(tensor_div), end='\n\n')
    print(sess.run(tensor_mod), end='\n\n')

[[ 4  4  4]
 [10 10 10]
 [16 16 16]]

[[-2  0  2]
 [-2  0  2]
 [-2  0  2]]

[[ 3  4  3]
 [24 25 24]
 [63 64 63]]

[[0.33333333 1.         3.        ]
 [0.66666667 1.         1.5       ]
 [0.77777778 1.         1.28571429]]

[[1 0 0]
 [4 0 2]
 [7 0 2]]



In [7]:
# https://www.tensorflow.org/api_docs/python/tf/math
tensor_add = tf.math.add(tensorA, tensorB)
tensor_sub = tf.math.subtract(tensorA, tensorB)
tensor_mul = tf.math.multiply(tensorA, tensorB)
tensor_div = tf.math.divide(tensorA, tensorB)
tensor_mod = tf.math.mod(tensorA, tensorB)

In [8]:
# create a session to run the tensors
with tf.Session() as sess:
    print(sess.run(tensor_add), end='\n\n')
    print(sess.run(tensor_sub), end='\n\n')
    print(sess.run(tensor_mul), end='\n\n')
    print(sess.run(tensor_div), end='\n\n')
    print(sess.run(tensor_mod), end='\n\n')

[[ 4  4  4]
 [10 10 10]
 [16 16 16]]

[[-2  0  2]
 [-2  0  2]
 [-2  0  2]]

[[ 3  4  3]
 [24 25 24]
 [63 64 63]]

[[0.33333333 1.         3.        ]
 [0.66666667 1.         1.5       ]
 [0.77777778 1.         1.28571429]]

[[1 0 0]
 [4 0 2]
 [7 0 2]]

